// ============================================================
//  Colon-Movies — Curated Blockbuster & IMDb Top Movies Catalog
// ============================================================

const MOVIES_CATALOG = [
  {
    id: 1,
    title: "Oppenheimer",
    year: "2023",
    released: "2023-07-21",
    runtime: 180,
    imdbRating: 8.9,
    genres: ["Biography", "Drama", "History"],
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6K9vY9wgjhCwMHudgGbR7mK9k.jpg",
    synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg"
  },
  {
    id: 2,
    title: "Dune: Part Two",
    year: "2024",
    released: "2024-03-01",
    runtime: 166,
    imdbRating: 8.8,
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b2S.jpg",
    synopsis: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w"
  },
  {
    id: 3,
    title: "Interstellar",
    year: "2014",
    released: "2014-11-07",
    runtime: 169,
    imdbRating: 8.7,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E"
  },
  {
    id: 4,
    title: "The Dark Knight",
    year: "2008",
    released: "2008-07-18",
    runtime: 152,
    imdbRating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Gary Oldman"],
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    synopsis: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY"
  },
  {
    id: 5,
    title: "Spider-Man: Across the Spider-Verse",
    year: "2023",
    released: "2023-06-02",
    runtime: 140,
    imdbRating: 8.7,
    genres: ["Animation", "Action", "Adventure"],
    director: "Joaquim Dos Santos, Kemp Powers",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Daniel Kaluuya"],
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    synopsis: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    trailerUrl: "https://www.youtube.com/embed/cqGjhVJWtEg"
  },
  {
    id: 6,
    title: "Inception",
    year: "2010",
    released: "2010-07-16",
    runtime: 148,
    imdbRating: 8.8,
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    synopsis: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0"
  },
  {
    id: 7,
    title: "The Batman",
    year: "2022",
    released: "2022-03-04",
    runtime: 176,
    imdbRating: 7.8,
    genres: ["Action", "Crime", "Drama"],
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright", "Colin Farrell"],
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tRS6jvPM9qPrrnx2KRx3ew96Yot.jpg",
    synopsis: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    trailerUrl: "https://www.youtube.com/embed/mqqft2x_Aa4"
  },
  {
    id: 8,
    title: "Blade Runner 2049",
    year: "2017",
    released: "2017-10-06",
    runtime: 164,
    imdbRating: 8.0,
    genres: ["Action", "Drama", "Mystery"],
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks"],
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/ilRyASDvt7v5qqQoK78eLqT5pmK.jpg",
    synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    trailerUrl: "https://www.youtube.com/embed/gCcx85zbxz4"
  },
  {
    id: 9,
    title: "Pulp Fiction",
    year: "1994",
    released: "1994-10-14",
    runtime: 154,
    imdbRating: 8.9,
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFnGhxvlUbFFmwa2DYflKd1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    trailerUrl: "https://www.youtube.com/embed/s7EdQ4FqbhY"
  },
  {
    id: 10,
    title: "Gladiator II",
    year: "2024",
    released: "2024-11-22",
    runtime: 148,
    imdbRating: 8.1,
    genres: ["Action", "Adventure", "Drama"],
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Pedro Pascal", "Denzel Washington", "Connie Nielsen"],
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnEx7vG5vtVHdnv.jpg",
    synopsis: "Years after witnessing the death of Maximus, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who rule Rome.",
    trailerUrl: "https://www.youtube.com/embed/4rgYUipGJNo"
  },
  {
    id: 11,
    title: "Avengers: Endgame",
    year: "2019",
    released: "2019-04-26",
    runtime: 181,
    imdbRating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    synopsis: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
    trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c"
  },
  {
    id: 12,
    title: "Parasite",
    year: "2019",
    released: "2019-10-11",
    runtime: 132,
    imdbRating: 8.5,
    genres: ["Drama", "Thriller"],
    director: "Bong Joon Ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    synopsis: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    trailerUrl: "https://www.youtube.com/embed/5xH0hhJk9X4"
  },
  {
    id: 13,
    title: "John Wick: Chapter 4",
    year: "2023",
    released: "2023-03-24",
    runtime: 169,
    imdbRating: 7.7,
    genres: ["Action", "Crime", "Thriller"],
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne"],
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefW0zZwhqYeinITv.jpg",
    synopsis: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances.",
    trailerUrl: "https://www.youtube.com/embed/qEVUtrk8_B4"
  },
  {
    id: 14,
    title: "Top Gun: Maverick",
    year: "2022",
    released: "2022-05-27",
    runtime: 130,
    imdbRating: 8.3,
    genres: ["Action", "Drama"],
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    synopsis: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a dangerous mission.",
    trailerUrl: "https://www.youtube.com/embed/giXco2jaZ_4"
  },
  {
    id: 15,
    title: "Fight Club",
    year: "1999",
    released: "1999-10-15",
    runtime: 139,
    imdbRating: 8.8,
    genres: ["Drama"],
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    synopsis: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    trailerUrl: "https://www.youtube.com/embed/qtRKdVHc-cE"
  },
  {
    id: 16,
    title: "Whiplash",
    year: "2014",
    released: "2014-10-10",
    runtime: 107,
    imdbRating: 8.5,
    genres: ["Drama", "Music"],
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist", "Paul Reiser"],
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhCzEN45YG3Wbk0om.jpg",
    synopsis: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    trailerUrl: "https://www.youtube.com/embed/7d_jQycdQGo"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = MOVIES_CATALOG;
}
